name: base_project
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# バージョンとビルド番号の指定
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons font for iOS style icons
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.0
  state_notifier: ^1.0.0
  flutter_riverpod: ^2.5.1
  flutter_state_notifier: ^1.0.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints to encourage good coding practices
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
